### ISSUE TITLE
Remove all codesandbox related content from the exercises

### ISSUE THREAD

**Issue by Roland-Hufnagel** [neuefische/web-exercises#370]
| **Assignees** | **Duration** |
| :------: | :--------: |
|   |   |

## Problem
Most exercises still contain codesandbox related content, e.g. a ``.codesandbox`` folder or a heading ``Codesandbox Cloud`` in the README.
Since we don't use Codesandbox anymore, this content should be removed. 

## Proposal
A script can be written that removes this content from all exercises.

**Comment by F-Kirchhoff** [comment]
Thats a good idea, I think we can even remove the .codesandbox files without a script.

**Comment by FelineHuhn** [comment]
Maybe I'm blind, but is the ticket still valid? 
After a quick check, I couldn't find any remaining Codesandbox content in Challenges and co. (except for an example implementation for Recap Project 2, which could remain read-only, right?). No .codesandbox folder or “Codesandbox Cloud” headings found.
